/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuildSupportRouteImport } from './routes/guild-support'
import { Route as GuildRewardsRouteImport } from './routes/guild-rewards'
import { Route as IndexRouteImport } from './routes/index'

const GuildSupportRoute = GuildSupportRouteImport.update({
  id: '/guild-support',
  path: '/guild-support',
  getParentRoute: () => rootRouteImport,
} as any)
const GuildRewardsRoute = GuildRewardsRouteImport.update({
  id: '/guild-rewards',
  path: '/guild-rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guild-rewards': typeof GuildRewardsRoute
  '/guild-support': typeof GuildSupportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guild-rewards': typeof GuildRewardsRoute
  '/guild-support': typeof GuildSupportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guild-rewards': typeof GuildRewardsRoute
  '/guild-support': typeof GuildSupportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/guild-rewards' | '/guild-support'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/guild-rewards' | '/guild-support'
  id: '__root__' | '/' | '/guild-rewards' | '/guild-support'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuildRewardsRoute: typeof GuildRewardsRoute
  GuildSupportRoute: typeof GuildSupportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/guild-support': {
      id: '/guild-support'
      path: '/guild-support'
      fullPath: '/guild-support'
      preLoaderRoute: typeof GuildSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guild-rewards': {
      id: '/guild-rewards'
      path: '/guild-rewards'
      fullPath: '/guild-rewards'
      preLoaderRoute: typeof GuildRewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuildRewardsRoute: GuildRewardsRoute,
  GuildSupportRoute: GuildSupportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
